#!/usr/bin/env python3
"""Fetch public repo metadata from GitHub API for each entry in _data/repositories.yml github_repos."""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Install PyYAML: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[2]
REPOS_YML = ROOT / "_data" / "repositories.yml"
OUT_YML = ROOT / "_data" / "repositories_stats.yml"
TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()


def github_get(path: str) -> dict:
    url = f"https://api.github.com{path}"
    headers = {
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "ammaryasirnaich-repo-stats-sync",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.loads(resp.read().decode())


def main() -> None:
    data = yaml.safe_load(REPOS_YML.read_text(encoding="utf-8"))
    repo_ids = data.get("github_repos") or []
    out: dict[str, dict] = {}

    for full in repo_ids:
        if not isinstance(full, str) or "/" not in full:
            continue
        owner, name = full.split("/", 1)
        try:
            j = github_get(f"/repos/{owner}/{name}")
            out[full] = {
                "stars": j.get("stargazers_count"),
                "forks": j.get("forks_count"),
                "language": j.get("language"),
                "pushed_at": j.get("pushed_at"),
            }
        except urllib.error.HTTPError as e:
            out[full] = {"error": f"HTTP {e.code}"}
        except Exception as e:
            out[full] = {"error": str(e)}

    header = (
        "# Auto-generated by .github/workflows/sync-repo-stats.yml\n"
        "# Do not edit by hand. Curated copy lives in repositories.yml\n\n"
    )
    OUT_YML.write_text(
        header + yaml.dump({"repos": out}, default_flow_style=False, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    print(f"Wrote {OUT_YML} ({len(out)} repos)")


if __name__ == "__main__":
    main()
